// قاموس المصطلحات العربية للتطبيق بأكمله
export const AR = {
  app: {
    title: 'المتخصص الذكي للعقارات',
    shortTitle: 'المتخصص العقاري',
    tagline: 'إدارة احترافية للأملاك والعقود بلا اتصال',
  },
  nav: {
    dashboard: 'لوحة المعلومات',
    properties: 'العقارات',
    customers: 'العملاء',
    contracts: 'العقود',
    payments: 'المدفوعات',
    reports: 'التقارير',
    settings: 'الإعدادات',
    financialReport: 'التقرير المالي',
    vacancyTracker: 'متابعة الشواغر',
    backup: 'النسخ الاحتياطي',
  },
  actions: {
    add: 'إضافة',
    edit: 'تعديل',
    delete: 'حذف',
    save: 'حفظ',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    search: 'بحث',
    filter: 'تصفية',
    close: 'إغلاق',
    view: 'عرض',
    print: 'طباعة',
    exportPdf: 'تصدير PDF',
    exportExcel: 'تصدير إكسل',
    exportJson: 'تصدير JSON',
    importJson: 'استيراد JSON',
    reset: 'إعادة تعيين',
    apply: 'تطبيق',
    clear: 'مسح',
    yes: 'نعم',
    no: 'لا',
    all: 'الكل',
    next: 'التالي',
    previous: 'السابق',
    submit: 'إرسال',
    installApp: 'تثبيت التطبيق',
  },
  common: {
    loading: 'جارٍ التحميل…',
    empty: 'لا توجد بيانات لعرضها',
    required: 'حقل مطلوب',
    invalid: 'قيمة غير صالحة',
    success: 'تمت العملية بنجاح',
    error: 'حدث خطأ',
    confirmDelete: 'هل أنت متأكد من الحذف؟',
    yes: 'نعم',
    no: 'لا',
    currency: 'ر.س',
    total: 'الإجمالي',
    count: 'العدد',
    date: 'التاريخ',
    from: 'من',
    to: 'إلى',
    status: 'الحالة',
    theme: 'السمة',
    light: 'فاتحة',
    dark: 'داكنة',
  },
  property: {
    name: 'اسم العقار',
    type: 'نوع العقار',
    status: 'الحالة',
    address: 'العنوان',
    city: 'المدينة',
    price: 'السعر / الإيجار السنوي',
    notes: 'ملاحظات',
    types: {
      apartment: 'شقة',
      villa: 'فيلا',
      building: 'عمارة',
      commercial: 'تجاري',
    },
    statuses: {
      vacant: 'شاغر',
      rented: 'مؤجر',
      sold: 'مباع',
      archived: 'مؤرشف',
    },
    minPrice: 'أقل سعر',
    maxPrice: 'أعلى سعر',
    addNew: 'إضافة عقار جديد',
    editTitle: 'تعديل بيانات العقار',
  },
  customer: {
    fullName: 'الاسم الكامل',
    nationalId: 'رقم الهوية / الإقامة',
    phone: 'رقم الجوال',
    email: 'البريد الإلكتروني',
    address: 'العنوان',
    city: 'المدينة',
    notes: 'ملاحظات',
    addNew: 'إضافة عميل جديد',
    editTitle: 'تعديل بيانات العميل',
  },
  contract: {
    property: 'العقار',
    customer: 'العميل',
    type: 'نوع العقد',
    startDate: 'تاريخ البدء',
    endDate: 'تاريخ الانتهاء',
    totalAmount: 'القيمة الإجمالية',
    paymentFrequency: 'دورية الدفع',
    remainingBalance: 'المتبقي',
    penaltyRate: 'نسبة الغرامة اليومية (%)',
    status: 'الحالة',
    types: { rent: 'إيجار', sale: 'بيع' },
    frequencies: {
      monthly: 'شهري',
      quarterly: 'ربع سنوي',
      annually: 'سنوي',
      one_time: 'دفعة واحدة',
    },
    statuses: {
      active: 'نشط',
      extended: 'ممدد',
      terminated: 'منتهي',
      canceled: 'ملغى',
      draft: 'مسودة',
    },
    addNew: 'إبرام عقد جديد',
    editTitle: 'تعديل العقد',
    generatedInvoices: 'الفواتير المُولدة',
  },
  payment: {
    contract: 'العقد',
    invoice: 'الفاتورة',
    amountPaid: 'المبلغ المسدد',
    paymentDate: 'تاريخ السداد',
    paymentMethod: 'طريقة السداد',
    referenceNumber: 'الرقم المرجعي',
    methods: {
      cash: 'نقداً',
      bank_transfer: 'حوالة بنكية',
      check: 'شيك',
      card: 'بطاقة',
    },
    statuses: {
      completed: 'مكتمل',
      partially_refunded: 'مسترد جزئياً',
      refunded: 'مسترد',
    },
    addNew: 'تسجيل دفعة',
    recordPayment: 'تسجيل سداد',
  },
  invoice: {
    number: 'رقم الفاتورة',
    dueDate: 'تاريخ الاستحقاق',
    amountDue: 'المبلغ المستحق',
    amountPaid: 'المبلغ المسدد',
    balance: 'الرصيد المتبقي',
    status: 'حالة الفاتورة',
    statuses: {
      paid: 'مسددة',
      partial: 'مسددة جزئياً',
      overdue: 'متأخرة',
      unpaid: 'غير مسددة',
    },
  },
  dashboard: {
    welcome: 'مرحباً بك في نظامك',
    totalProperties: 'إجمالي العقارات',
    activeContracts: 'العقود النشطة',
    totalCustomers: 'إجمالي العملاء',
    monthlyIncome: 'دخل الشهر',
    overdueInvoices: 'فواتير متأخرة',
    occupancyRate: 'نسبة الإشغال',
    upcomingDues: 'الاستحقاقات القادمة',
    recentActivity: 'أحدث النشاطات',
    revenueByMonth: 'الإيرادات الشهرية',
    propertyDistribution: 'توزيع العقارات',
    noUpcoming: 'لا توجد استحقاقات قريبة',
    noActivity: 'لم تُسجل أي نشاطات بعد',
  },
  settings: {
    profile: 'ملف الشركة',
    ownerName: 'اسم المالك',
    companyName: 'اسم الشركة / المؤسسة',
    phone: 'الهاتف',
    email: 'البريد الإلكتروني',
    taxNumber: 'الرقم الضريبي',
    currency: 'العملة',
    theme: 'المظهر',
    enableNotifications: 'تفعيل الإشعارات المحلية',
    backupTitle: 'النسخ الاحتياطي والاستعادة',
    backupDesc: 'حفظ كامل قاعدة البيانات في ملف JSON على جهازك، أو استعادتها من ملف سابق.',
    dangerZone: 'المنطقة الحساسة',
    resetAll: 'حذف جميع البيانات',
    resetWarning: 'سيتم حذف كل السجلات نهائياً من متصفحك. لا يمكن التراجع.',
    saveSettings: 'حفظ الإعدادات',
  },
  reports: {
    financialTitle: 'التقرير المالي الشامل',
    vacancyTitle: 'متابعة العقارات الشاغرة والمؤجرة',
    period: 'الفترة',
    generate: 'إنشاء التقرير',
    revenue: 'الإيرادات',
    expenses: 'المصروفات',
    net: 'صافي الدخل',
  },
  offline: 'وضع بدون اتصال',
  online: 'متصل',
  updated: 'تحديث جديد متوفر — اضغط لإعادة التحميل',
} as const;

export const CITIES_SA = [
  'الرياض', 'جدة', 'مكة المكرمة', 'المدينة المنورة', 'الدمام', 'الخبر', 'الظهران',
  'الطائف', 'تبوك', 'أبها', 'خميس مشيط', 'حائل', 'الجبيل', 'ينبع', 'بريدة',
  'عنيزة', 'نجران', 'جازان', 'الأحساء', 'القطيف', 'الباحة', 'عرعر', 'سكاكا',
];
